### ISSUE TITLE
about Sepformer，why two FeedForward？

### ISSUE THREAD

**Issue by zuowanbushiwo** [rijalsankalp/perceparator#7]
Hi @rijalsankalp  @VoidCU 
      I found that the Sepformer you implemented is somewhat different from speechbrain and [Zhongyang-debug/Attention-Is-All-You-Need-In-Speech-Separation](https://github.com/Zhongyang-debug/Attention-Is-All-You-Need-In-Speech-Separation), but yours is closer to the original paper description? But your Sepformer has two FFW,  why?  Also what are your test results?
thanks！

**Comment by rijalsankalp** [comment]
No this is not the implementation of the original paper, but an attempt to implement a different kind of transformer model, which reduces quadratic complexity problem of the original transformer architecture. We have tried to use the transformer architecture suggested in [Perceiver: General Perception with Iterative Attention](https://arxiv.org/pdf/2103.03206v2.pdf). 
For the case of two FFW, they are  being used to scale the latent array (it has less dims than the input data) to the original shape before decoding the separated audio.
No test results as of now, we're still training our model and it may need several changes.
